### ISSUE TITLE
Late filter for segmentID

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/vitrivr-ng#51]
For debugging purposes, it would be rather useful to have a text-field where you can late filter by segmentID.

**Comment by lucaro** [comment]
In that context, a 'jump to segment' function would also be nice. This would also make the collabordinator much more useful.

**Comment by silvanheller** [comment]
> 
> 
> In that context, a 'jump to segment' function would also be nice. This would also make the collabordinator much more useful.

I'm not sure how that feature would be implemented or how it would make the collabordinator more useful. The current implementation of the filter hides all elements which do not match the id for either object or segmentid

**Comment by lucaro** [comment]
If you are filtering for a specific id, the filter only shows you if its there or not, by either showing you an almost or completely empty result list. If you would rather jump to any particular element, you can also see it in its context. Such functionality could be re-used in the context of the collabordinator, since it synchronizes ids. So if you were wanting to look at something somebody else already marked, it would enable you to go there directly, rather than scrolling until you find an element with the right color.
