### ISSUE TITLE
"AND" of boolean queries

### ISSUE THREAD

**Issue by RibinMTC** [vitrivr/vitrivr-ng#53]
Dear devs,

When I apply two boolean queries, can do a logical "AND" on the results?

Best,

Ribin

**Comment by silvanheller** [comment]
The currently implemented semantic is already an AND if you have multiple boolean conditions in the same query box.

**Comment by RibinMTC** [comment]
Ok, and is it possible to show only the results satisfying both conditions? I think currently all results are shown, sorted by the score.

**Comment by silvanheller** [comment]
Then i confess i don't understand your question. If you use two dropdowns like this it should only show results which match both conditions:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/14314470/98530487-43e1e200-227f-11eb-8f94-1d2d5b09e910.png">

**Comment by RibinMTC** [comment]
Hey, I think the problem is that I added sorting order to one of the boolean queries, that this somehow leads to showing all results?
![BooleanAndError](https://user-images.githubusercontent.com/72801998/98533983-0e8bc300-2284-11eb-8abb-2222a48a416e.PNG)

**Comment by silvanheller** [comment]
Well it depends on how your feature is implemented. In the `BooleanRetriever`, the `getRowsAND` method of the selector is used (at least in the current master-branch), but if you implemented that differently then it's possible a different semantic is used.

**Comment by RibinMTC** [comment]
Hi Silvian,

I did use the _getRowsAND_ method, however this retriever is only implemented for the _AestheticScore_ feature, since sorting was only required for it. Below I have included the implementation for the Retriever class with the cineast.json config file.
[SortedAestheticScoreRetriever.zip](https://github.com/vitrivr/vitrivr-ng/files/5531826/SortedAestheticScoreRetriever.zip)

**Comment by silvanheller** [comment]
I saw you stuck the the `RangeBooleanRetriever` feature rather closely. I think there's some misunderstandings here:
- We had a bug in our `populateExtremaMap` method which is fixed on dev now: In you class on Line 70, max and t should be switched, correct would be `compare(t, max)`
- I don't understand why you're retrieving the id and feature column separately. You can simply add the feature column to your projection by replacing `Collections.singletonList("id")` with `Lists.newArrayList("id", "feature")`

I think the issue lies in the misconfiguration of your feature. You made two features:
```
	{	"feature":  "SortedByAestheticScoreRetriever", "weight": 1.0,
		"properties": 
	 	{
			"entity": "features_aestheticscore",
			"attribute": "feature"
		}	
	},
	{
		"feature":  "RangeBooleanRetriever", "weight": 1.0,
		"properties": 
	 	{
			"entity": "features_facialemotion",
			"attribute": "feature"
		}
	}
```
So of course cineast will return results for both features since there is an OR-semantic between two different features. If you use the debugger of your IDE (e.g. IntelliJ), you will see that the queries get executed in separate features. If you wish to only show results matching both features, you'll either have to use just one feature as currently possible in the `RangeBooleanRetriever` or wait for https://github.com/vitrivr/cineast/issues/157. Alternatively, you can simply modify the frontend.

**Comment by RibinMTC** [comment]
Thanks for the detailed answer Silvian. Could you further clarify what you mean by modifying the frontend?

**Comment by silvanheller** [comment]
There is currently no feature which uses multiple tables AFAIK. But you can implement that yourself, there should not be anything limiting you to just one table in your feature implementation. You can change which table a selector is accessing using the `open` method.

**Comment by RibinMTC** [comment]
Hi Silvan,

Due to my project requirements, I need to have different Retrievers for different features. Could explain what I would need to modify in the frontend to get the "AND"ing with multiple Retrievers(https://github.com/vitrivr/vitrivr-ng/issues/53#issuecomment-726296651)?

**Comment by silvanheller** [comment]
If they need to be in the same category, then you probably rather need to modify Cineast. Have a look at how the result are merged in a category at https://github.com/vitrivr/cineast/blob/e700e9356b13a8d4a1a9ac6248a2858c85ada4d9/cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/runtime/ContinuousQueryDispatcher.java#L155.

But as I said previously in this thread, you're probably better off creating a new feature which receives your boolean query and calculates a score per segmentid - this is how Cineast is set up.

The quickest fix, but I'm not sure if that fits your use case, is to simply filter results in the frontend with a score below a certain threshold by adding another filter pipe (e.g. at https://github.com/vitrivr/vitrivr-ng/blob/a09ea8a302c1870dc137289302a341c52d85ea76/src/app/results/gallery/mini-gallery.component.html#L12). If you have two features for your category, and one returns scores of 0 or 1, then all elements which match both features will have a score of above 0.5 (since all matches for the binary score feature will contribute 0.5 to the score for this category)
